<?php
defined('ABSPATH') || exit;
$asset_base = plugins_url('assets/', dirname(__DIR__) . '/pcw-renew48-blocks.php');
$wrapper = get_block_wrapper_attributes(array('class' => 'pcw-r48-block pcw-r48-unleashed-article', 'data-pcw-article' => 'unleashed', 'style' => '--ua-hero:url(' . esc_url($asset_base . 'unleashed-hero-desert.png') . ');--ua-question:url(' . esc_url($asset_base . 'unleashed-question-desert.png') . ');--ua-healing:url(' . esc_url($asset_base . 'unleashed-healing-photo.png') . ');--ua-movement:url(' . esc_url($asset_base . 'unleashed-movement-photo.png') . ');--ua-wellness:url(' . esc_url($asset_base . 'unleashed-wellness-photo.png') . ');--ua-personal:url(' . esc_url($asset_base . 'unleashed-personal-photo.png') . ');'));
?>
<article <?php echo $wrapper; ?>>
    <aside class="pcw-r48-article-rail" aria-label="Unleashed navigation">
        <div class="pcw-r48-rail-mark"><span class="pcw-r48-leaf-icon" aria-hidden="true">⌁</span><strong>RENEW48</strong><small>WELLNESS<br>COLLECTIVE</small></div>
        <nav><a href="#healing"><span>✧</span>Healing</a><a href="#movement"><span>⌁</span>Movement</a><a href="#wellness"><span>◌</span>Wellness</a></nav>
        <button class="pcw-r48-rail-menu" type="button" aria-label="Open article menu"><span></span><span></span><span></span><small>MENU</small></button>
        <p class="pcw-r48-rail-quote">Rooted in the desert.<br>Elevated by care.<br>Inspired by movement.</p>
    </aside>
    <div class="pcw-r48-article-main">
        <header class="pcw-r48-article-header"><div><h1>UNLEASHED</h1><p>The official blog of Renew48</p></div><div class="pcw-r48-article-nav"><span>Mind</span><i>|</i><span>Body</span><i>|</i><span>Soul</span></div><div class="pcw-r48-article-partners"><span>Chiro<span>GoAZ</span><small>COLLECTIVE MEMBER</small></span><span>Aroma<span>HMT</span><small>COLLECTIVE MEMBER</small></span></div></header>
        <section class="pcw-r48-article-hero pcw-r48-motion-target"><div class="pcw-r48-hero-copy"><div class="pcw-r48-post-meta"><strong>POST 01</strong><span>Tuesday, August 18, 2026</span><span>By Renew48</span></div><h2>Committed to Wellness:<br>A Better Approach to<br>Whole-Person Care</h2><div class="pcw-r48-rule"></div><p class="pcw-r48-hero-tagline">Healing. Movement. Wellness. — Here for you.</p><div class="pcw-r48-share">Share: <button aria-label="Share on Facebook">f</button><button aria-label="Share on Instagram">◎</button><button aria-label="Share on LinkedIn">in</button><button aria-label="Copy link">↗</button></div></div><div class="pcw-r48-hero-art"><div class="pcw-r48-desert-scene" aria-label="Animated desert sunrise image"><img class="pcw-r48-hero-image" src="<?php echo esc_url($asset_base . 'unleashed-hero-desert.png'); ?>" alt="Sonoran desert at sunrise with saguaro cactus"></div><img class="pcw-r48-botanical-overlay" src="<?php echo esc_url($asset_base . 'unleashed-botanical-overlay.svg'); ?>" alt=""></div></section>
        <section class="pcw-r48-idea-panel pcw-r48-motion-target"><div class="pcw-r48-round-icon">⌁</div><div><h3>The Big Idea</h3><p>Whole-person wellness is not about adding to your checklist. It is about understanding how movement, recovery, stress, rest, connection, and care work together—and creating support around the whole you.</p></div><span class="pcw-r48-idea-sprig">⌁</span></section>
        <section class="pcw-r48-article-intro pcw-r48-motion-target"><div><p>If you live in the Phoenix Valley, you probably know what it means to push through heat. Whether you are navigating the intense summer heat, recovering from an active weekend on the trails, or managing the daily hustle, it’s all too easy to view our health as a mere checklist—seeking a quick fix for a sore back or an hour of relief from stress.</p><p>But true whole-person wellness goes beyond a single appointment, habit, or product. It’s about freeing yourself from the pain you didn’t know you had—whether that pain is physical, mental, or emotional. It is about how the pieces of your life work together: how you move, recover, manage stress, rest, connect, and make choices that support the person you want to be.</p><p>Recognizing the need for a more connected approach right here in our community is the foundation of Committed to Wellness, a shared direction from Renew48 and our collective members.</p></div><aside class="pcw-r48-question-card"><div class="pcw-r48-round-icon">?</div><h3>A Better Question</h3><p>Instead of asking only, “What is bothering you today?” whole-person care also asks: “What are you trying to get back to?”</p></aside></section>
        <p class="pcw-r48-article-pullquote">Maybe that is moving comfortably, returning to a favorite activity, creating space to recover, or finally releasing tension you’ve been carrying for years without realizing it.</p>
        <section id="healing" class="pcw-r48-angle-section pcw-r48-motion-target"><div class="pcw-r48-section-number">02</div><div class="pcw-r48-section-heading"><h2>Wellness from Every Angle</h2><p>Committed to Wellness brings together complementary perspectives across the Renew48 collective to help you uncover and address those hidden roadblocks:</p></div><div class="pcw-r48-angle-grid"><article><div class="pcw-r48-round-icon">✧</div><h3>Healing</h3><p>Therapeutic massage and restorative care create space for recovery, relaxation, and mindful self-care.</p></article><article id="movement"><div class="pcw-r48-round-icon">⌁</div><h3>Movement</h3><p>A movement-focused approach helps people better understand how their bodies move and function.</p></article><article id="wellness"><div class="pcw-r48-round-icon">◌</div><h3>Wellness</h3><p>Together, we connect everyday choices with a more purposeful approach to your well-being.</p></article></div><div class="pcw-r48-bottom-note">The goal is not to force everyone into the same path. It is to create a clearer, more coordinated experience where you can discover services, ask better questions, and choose the support that makes sense for you.</div></section>
        <section class="pcw-r48-personal-section pcw-r48-motion-target"><div class="pcw-r48-section-number">03</div><div class="pcw-r48-section-heading"><h2>Care Should Feel<br>Personal, Not<br>Transactional</h2></div><article class="pcw-r48-listen-card"><div class="pcw-r48-round-icon">♡</div><h3>Listen First</h3><p>Your goals, preferences, schedule, comfort level, and lived experiences matter. Care should create room for conversation, clarity, and informed choice—not a one-size-fits-all checklist.</p></article><div class="pcw-r48-personal-copy"><p>Renew48 is built around the idea that stronger wellness ecosystems are local and relational. When trusted providers, practitioners, and community members share knowledge and support one another, wellness becomes easier to navigate—and undeniably more human.</p><p>For us, “committed” means showing up with consistency: creating welcoming experiences, collaborating where it adds value, and continuing to improve how our collective supports the community.</p></div></section>
        <section class="pcw-r48-next-section pcw-r48-motion-target"><div class="pcw-r48-section-number">04</div><div class="pcw-r48-section-heading"><h2>Your Next Step</h2><p>Start with the question that matters most to you. Explore the Renew48 collective, learn about available services, and choose the next step that aligns with your goals.</p></div><a class="pcw-r48-next-card pcw-r48-next-card-dark" href="#collective"><span class="pcw-r48-round-icon">♧</span><strong>Explore the collective</strong><small>Discover Renew48, ChiroGoAZ, and Aroma HMT.</small><span class="pcw-r48-arrow">→</span></a><a class="pcw-r48-next-card" href="#unleashed"><span class="pcw-r48-round-icon">▣</span><strong>Continue Unleashed →</strong><small>New insight every Tuesday.</small><span class="pcw-r48-arrow">→</span></a></section>
        <footer class="pcw-r48-seo-panel"><h3>SEO &amp; Publishing</h3><div><span><b>SEO title</b>Committed to Wellness: A Better Approach to Whole-Person Care | Renew48</span><span><b>Description</b>Discover Renew48’s whole-person approach to wellness and how healing, movement, restorative care, and community come together.</span><span><b>Suggested slug</b>/unleashed/committed-to-wellness/</span><span><b>Primary keyphrase</b>whole-person wellness</span><span><b>Social excerpt</b>Wellness is bigger than a single appointment. Discover how Renew48 brings healing, movement, restorative care, and community together.</span></div></footer>
        <div class="pcw-r48-article-footer">ROOTED IN THE DESERT <b>•</b> ELEVATED BY CARE <b>•</b> INSPIRED BY MOVEMENT.</div>
    </div>
</article>
