<?php
/** Desert Liquid Glass general-purpose Astra-compatible theme. */
defined('ABSPATH') || exit;
const DLG_VERSION = '0.1.4';
const DLG_THEME_META = '_dlg_theme';
const DLG_MODE_META = '_dlg_mode';
const DLG_MEDIA_META = '_dlg_page_media';

function dlg_themes(): array { return array(
  'arizona-sky'=>array('label'=>'Arizona Sky','canvas'=>'#edf2f1','surface'=>'#f5f7f3','glass'=>'rgba(238,246,245,.70)','text'=>'#173a38','primary'=>'#1f635e','accent'=>'#d48745','border'=>'rgba(31,99,94,.24)','focus'=>'#d48745','blur'=>'18px'),
  'endless-skies'=>array('label'=>'Endless Skies','canvas'=>'#e8eef2','surface'=>'#f5f8fa','glass'=>'rgba(235,244,250,.68)','text'=>'#16384d','primary'=>'#245c7d','accent'=>'#d78d46','border'=>'rgba(36,92,125,.24)','focus'=>'#d78d46','blur'=>'18px'),
  'first-light'=>array('label'=>'First Light','canvas'=>'#fbf2e8','surface'=>'#fff9f2','glass'=>'rgba(255,248,240,.72)','text'=>'#423126','primary'=>'#76503c','accent'=>'#d06a3f','border'=>'rgba(118,80,60,.22)','focus'=>'#d06a3f','blur'=>'17px'),
  'jane-aire-dark'=>array('label'=>'Jane-Aire Dark','canvas'=>'#101619','surface'=>'#1c2528','glass'=>'rgba(25,36,40,.72)','text'=>'#f7f1e8','primary'=>'#b9d1c1','accent'=>'#e0ad63','border'=>'rgba(255,255,255,.25)','focus'=>'#f6d58f','blur'=>'20px'),
  'morning-haze'=>array('label'=>'Morning Haze','canvas'=>'#f1eee9','surface'=>'#faf9f6','glass'=>'rgba(250,248,243,.73)','text'=>'#39443f','primary'=>'#596b60','accent'=>'#be7753','border'=>'rgba(89,107,96,.23)','focus'=>'#be7753','blur'=>'17px'),
  'neon-nights'=>array('label'=>'Neon Nights','canvas'=>'#0b1422','surface'=>'#17243a','glass'=>'rgba(16,34,59,.74)','text'=>'#f6f8ff','primary'=>'#4cb7ff','accent'=>'#f3bb62','border'=>'rgba(107,193,255,.34)','focus'=>'#f4d487','blur'=>'22px'),
  'red-rocks'=>array('label'=>'Red Rocks','canvas'=>'#f3e9df','surface'=>'#fbf3eb','glass'=>'rgba(250,239,229,.70)','text'=>'#492f2a','primary'=>'#8a4d3d','accent'=>'#cf7a3d','border'=>'rgba(138,77,61,.25)','focus'=>'#cf7a3d','blur'=>'18px'),
  'tropical-oasis'=>array('label'=>'Tropical Oasis','canvas'=>'#e7f1eb','surface'=>'#f3faf5','glass'=>'rgba(235,248,239,.69)','text'=>'#174339','primary'=>'#23705c','accent'=>'#d48c4d','border'=>'rgba(35,112,92,.24)','focus'=>'#d48c4d','blur'=>'18px'),
  'pcwprops'=>array('label'=>'PCWProps','canvas'=>'#06152c','surface'=>'#0f2343','glass'=>'rgba(10,28,57,.75)','text'=>'#f5f8ff','primary'=>'#1e9bd7','accent'=>'#f2c76b','border'=>'rgba(242,199,107,.36)','focus'=>'#f2c76b','blur'=>'22px'),
 ); }
function dlg_theme_settings(): array {
  $settings = get_option('dlg_settings', array());
  return wp_parse_args(is_array($settings) ? $settings : array(), array(
    'default_theme' => 'arizona-sky',
    'default_mode' => 'contained',
    'reduce_motion' => 'respect-system',
    'performance' => 'balanced',
  ));
}
function dlg_sanitize_media($value): array { $v=is_array($value)?$value:array(); return array('url'=>esc_url_raw((string)($v['url']??'')),'mobileUrl'=>esc_url_raw((string)($v['mobileUrl']??'')),'position'=>sanitize_text_field((string)($v['position']??'center center')),'mobilePosition'=>sanitize_text_field((string)($v['mobilePosition']??'center center')),'size'=>in_array(($v['size']??'cover'),array('cover','contain','auto'),true)?$v['size']:'cover','overlay'=>sanitize_text_field((string)($v['overlay']??'medium'))); }
add_action('after_setup_theme',static function():void{add_theme_support('align-wide');add_theme_support('responsive-embeds');add_theme_support('woocommerce');add_theme_support('custom-logo',array('height'=>92,'width'=>420,'flex-height'=>true,'flex-width'=>true));add_theme_support('editor-styles');add_editor_style('style.css');});
add_action('init',static function():void{register_post_meta('page',DLG_THEME_META,array('type'=>'string','single'=>true,'show_in_rest'=>true,'sanitize_callback'=>static fn($v)=>array_key_exists($v,dlg_themes())?$v:'arizona-sky','auth_callback'=>static fn()=>current_user_can('edit_pages')));register_post_meta('page',DLG_MODE_META,array('type'=>'string','single'=>true,'show_in_rest'=>true,'sanitize_callback'=>static fn($v)=>in_array($v,array('contained','masked','full'),true)?$v:'contained','auth_callback'=>static fn()=>current_user_can('edit_pages')));register_post_meta('page',DLG_MEDIA_META,array('type'=>'object','single'=>true,'show_in_rest'=>true,'sanitize_callback'=>'dlg_sanitize_media','auth_callback'=>static fn()=>current_user_can('edit_pages')));});
add_action('wp_enqueue_scripts',static function():void{wp_enqueue_style('desert-liquid-glass',get_stylesheet_uri(),array('astra-theme-css'),DLG_VERSION);if(!is_singular('page'))return;$id=get_queried_object_id();$defaults=dlg_theme_settings();$theme=get_post_meta($id,DLG_THEME_META,true);$theme=array_key_exists($theme,dlg_themes())?$theme:$defaults['default_theme'];$theme=array_key_exists($theme,dlg_themes())?$theme:'arizona-sky';$tokens=dlg_themes()[$theme];$media=dlg_sanitize_media(get_post_meta($id,DLG_MEDIA_META,true));$overlay=array('none'=>'transparent','light'=>'rgba(8,26,23,.12)','medium'=>'rgba(8,26,23,.28)','strong'=>'rgba(8,26,23,.46)');$vars=array('--dlg-page-media'=>$media['url']?'url("'.esc_url($media['url']).'")':'none','--dlg-page-media-mobile'=>$media['mobileUrl']?'url("'.esc_url($media['mobileUrl']).'")':'var(--dlg-page-media)','--dlg-media-position'=>$media['position'],'--dlg-media-position-mobile'=>$media['mobilePosition'],'--dlg-media-size'=>$media['size'],'--dlg-page-overlay'=>$overlay[$media['overlay']]??$overlay['medium']);foreach($tokens as $key=>$value)$vars['--dlg-'.$key]=$value;$css='body.dlg-page-shell{'.implode(';',array_map(static fn($k,$v)=>$k.':'.$v,array_keys($vars),array_values($vars))).'}';wp_add_inline_style('desert-liquid-glass',$css);});
add_filter('body_class',static function(array $classes):array{if(!is_singular('page'))return $classes;$defaults=dlg_theme_settings();$mode=get_post_meta(get_queried_object_id(),DLG_MODE_META,true);$mode=in_array($mode,array('contained','masked','full'),true)?$mode:$defaults['default_mode'];$classes[]='dlg-page-shell';$classes[]='dlg-mode-'.sanitize_html_class($mode);return $classes;});
add_filter('get_custom_logo',static function($html):string{if($html)return (string)$html;$src=get_stylesheet_directory_uri().'/assets/renew48-wordmark.svg';return '<a class="custom-logo-link" href="'.esc_url(home_url('/')).'" rel="home"><img class="custom-logo" src="'.esc_url($src).'" alt="'.esc_attr(get_bloginfo('name')).'"></a>';});
add_action('init',static function():void{wp_register_style('desert-liquid-glass',get_stylesheet_uri(),array('astra-theme-css'),DLG_VERSION);foreach(array('container','section','grid','flex-row','flex-column','spacer','divider','hero-primary','cinematic-hero','hero-split','hero-video','cta-banner','service-card','service-grid','service-comparison','service-accordion','faq-accordion','testimonial-slider','blog-preview','education-grid','glass-panel','liquid-glass','acrylic-card','neon-accent','parallax-layer','hover-reveal','scroll-reveal','header-cta','footer-columns','navigation-panel','breadcrumbs','alert-banner','carousel-slide','modal-trigger','gallery-lightbox','tabbed-content','newsletter-capture','social-proof-strip','pricing-grid') as $slug)register_block_type('dlg/'.$slug,array('render_callback'=>'dlg_render_block','style'=>'desert-liquid-glass','attributes'=>array('title'=>array('type'=>'string','default'=>ucwords(str_replace('-',' ',$slug))),'body'=>array('type'=>'string','default'=>''),'mediaUrl'=>array('type'=>'string','default'=>''),'mediaAlt'=>array('type'=>'string','default'=>''),'surface'=>array('type'=>'string','default'=>'solid'))));});
add_action('enqueue_block_editor_assets',static function():void{wp_enqueue_script('dlg-editor',get_stylesheet_directory_uri().'/assets/editor.js',array('wp-blocks','wp-element','wp-block-editor','wp-components','wp-data','wp-edit-post','wp-plugins'),DLG_VERSION,true);});
function dlg_render_block(array $attributes,string $content='', $block=null):string{$slug=$block&&isset($block->name)?sanitize_html_class(str_replace('dlg/','',(string)$block->name)):'generic';$title=esc_html((string)($attributes['title']??''));$body=wp_kses_post(wpautop((string)($attributes['body']??'')));$media=esc_url((string)($attributes['mediaUrl']??''));$alt=esc_attr((string)($attributes['mediaAlt']??''));$surface=sanitize_html_class((string)($attributes['surface']??'solid'));$media_markup=$media?'<img src="'.$media.'" alt="'.$alt.'" loading="lazy">':'';$media_class=$media?' has-component-media':'';return '<section class="dlg-block dlg-'.$slug.' dlg-surface is-surface-'.esc_attr($surface).$media_class.'"><div class="dlg-surface__media">'.$media_markup.'</div><div class="dlg-surface__material"></div><div class="dlg-surface__content"><h2>'.$title.'</h2><div>'.$body.'</div>'.$content.'</div></section>';}
require_once __DIR__.'/admin.php';
